#!/usr/bin/python3
#
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 tw=100 et ai si
#
# Copyright (C) 2019-2025 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause
#
# Author: Artem Bityutskiy <artem.bityutskiy@linux.intel.com>

"""
stc-agent-ipmi-helper - a wrapper over the 'ipmitool' utility for collecting the IPMI statistics.
This is an internal sub-tool of the 'stats-collect' tool, not intended to be used directly by end
users.
"""

from statscollecttools._STCAgentIPMIHelper import main

if __name__ == "__main__":
    raise SystemExit(main())
