#!/usr/bin/python3
#
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 tw=100 et ai si
#
# Copyright (C) 2022-2025 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause
#
# Author: Artem Bityutskiy <artem.bityutskiy@linux.intel.com>

"""
stc-wl-cpu-wake-walk - a stats-collect workload for measuring an idle CPU which wakes up with
certain wake period (launch distance). Walk through user-specified wake periods.
"""

from statscollecttools._STCWLCPUWakeWalk import main

if __name__ == "__main__":
    raise SystemExit(main())
