#!/usr/bin/python3
#
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 tw=100 et ai si
#
# Copyright (C) 2025-2026 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause
#
# Author: Artem Bityutskiy <artem.bityutskiy@linux.intel.com>

"""
stc-wl-cpu-freq-walk - a stats-collect workload for measuring the system while locking CPU frequency
at different levels.
"""

from statscollecttools._STCWLCPUFreqWalk import main

if __name__ == "__main__":
    raise SystemExit(main())
