#!/usr/bin/python3
#
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 tw=100 et ai si
#
# Copyright (C) 2019-2025 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause
#
# Author: Artem Bityutskiy <artem.bityutskiy@linux.intel.com>

"""
stc-agent - the statistics collection agent, a service for collecting statistics. This is an
internal sub-tool of the 'stats-collect' tool, not intended to be used directly by end users.
"""

import sys
from pathlib import Path

try:
    # pylint: disable-next=unused-import
    import pepclibs  # noqa: F401
except ImportError:
    # 'pepclibs' is not installed. It may be in the sibling 'pepc' source directory.
    _pepcroot = Path(__file__).parent / "pepc"
    sys.path.insert(0, str(_pepcroot))
    sys.modules.pop("pepclibs", None)

from statscollecttools._STCAgent import main

if __name__ == "__main__":
    raise SystemExit(main())
