PREFIX ?= /tmp/stc-wl
BINDIR := $(PREFIX)/bin
TOOLNAMES = stc-wl-cpu-wake-walk

all:
	

clean:
	

install:
	mkdir -p $(BINDIR)
	cp stc-wl-cpu-wake-walk.standalone $(BINDIR)/stc-wl-cpu-wake-walk

uninstall:
	rm -f $(BINDIR)/stc-wl-cpu-wake-walk
	rmdir --ignore-fail-on-non-empty $(BINDIR)
