#!/usr/bin/python3
#
# -*- coding: utf-8 -*-
# vim: ts=4 sw=4 tw=100 et ai si
#
# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause
#
# Author: Artem Bityutskiy <artem.bityutskiy@linux.intel.com>

"""
install-stats-collect - install 'stats-collect' on the local or remote host.
"""

from statscollecttools import InstallStatsCollect

if __name__ == "__main__":
    raise SystemExit(InstallStatsCollect.main())
